# name: Server Health Check

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build-node:
#     runs-on: ubuntu-latest
#     container: node:14
#     steps:
#       - name: Check Node.js and npm versions
#         run: |
#           node --version
#           npm --version
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Run server.js
#         run: |
#           cd server/
#           npm install
#           npm start
#       - name: Check Server Health
#         run: |
#           response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000)
#           if [ "$response" = "200" ]; then
#             echo "Server is running and healthy (HTTP 200 OK)"
#           else
#             echo "Server is not running or healthy (HTTP $response)"
#             exit 1
#           fi
#       - name: Stop the Server
#         run: pkill -f "node server.js" || true
